- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Install PHP
  apt:
    name: php
    state: present

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - ssl

- name: Configure Apache virtual host
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/mysite.conf

- name: Enable Apache virtual host
  command: a2ensite mysite.conf

- name: Restart Apache
  service:
    name: apache2
    state: restarted
