---
- name: Import install_tools playbook
  import_playbook: playbooks/install_tools.yml

- name: Verify installation
  hosts: all
  become: yes
  tasks:
    - name: Display completion message
      debug:
        msg: "Tools installation completed on {{ inventory_hostname }}"
