- name: Download Splunk
  get_url:
    url: "https://download.splunk.com/products/splunk/releases/7.1.1/linux/splunk-7.1.1-8f0ead9ec3db-linux-2.6-amd64.deb"
    dest: "/tmp/splunk.deb"

- name: Install Splunk
  apt:
    deb: "/tmp/splunk.deb"
    state: present

- name: Start Splunk
  command: "/opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt"

- name: Configure Splunk inputs
  template:
    src: inputs.conf.j2
    dest: /opt/splunk/etc/system/local/inputs.conf

- name: Configure Splunk outputs
  template:
    src: outputs.conf.j2
    dest: /opt/splunk/etc/system/local/outputs.conf

- name: Restart Splunk
  command: "/opt/splunk/bin/splunk restart"
