- name: Install Active Directory
  ansible.windows.win_feature:
       name: AD-Domain-Services
       include_management_tools: yes
       include_sub_features: yes
       state: present
  register: result

- name: Install DNS Server
  win_feature:
    name: DNS
    state: present
    include_management_tools: yes

- name: Install DHCP Server
  win_feature:
    name: DHCP
    state: present
    include_management_tools: yes

- name: Create Domain
  microsoft.ad.domain:
     dns_domain_name: "{{ domain_name }}"
     safe_mode_password: "{{ recovery_password }}"
     sysvol_path: C:\Windows\SYSVOL
     database_path: C:\Windows\NTDS
  register: domain_install

- name: Reboot server if required
  ansible.windows.win_reboot:
  when: domain_install.reboot_required

- name: Check if DNS forwarder 1.1.1.1 exists
  win_shell: |
    $forwarders = Get-DnsServerForwarder | Select-Object -ExpandProperty IPAddress
    if ($forwarders -contains '1.1.1.1') {
      Write-Output 'Exists'
    } else {
      Write-Output 'NotExists'
    }
  register: dns_forwarder_check

- name: Add DNS forwarder 1.1.1.1 if not present
  win_shell: |
    Add-DnsServerForwarder -IPAddress '1.1.1.1'
  when: "'NotExists' in dns_forwarder_check.stdout"

- name: Configure DNS Server
  community.windows.win_dns_zone:
    name: example.com
    type: primary
    dynamic_update: secure

- name: Configure DHCP Server
  community.windows.win_dhcp_lease:
    name: Default
    start_range: "{{ dhcp_start }}"
    end_range: "{{ dhcp_end }}"
    subnet_mask: "{{ dhcp_subnet_mask }}"
    state: present

# This takes a while due to users and groups - hence the tag
- name: Configure AD
  include_tasks: configure_AD.yaml
  tags: configure_ad