- name: Transfer Python package
  copy:
    src: python-kitchen-1.2.6-9.el9.src.rpm
    dest: /tmp/python-kitchen-1.2.6-9.el9.src.rpm

- name: Transfer YUM package
  copy:
    src: yum-utils-1.1.31-28.fc21.noarch.rpm
    dest: /tmp/yum-utils-1.1.31-28.fc21.noarch.rpm

- name: Install Python using RPM
  command: rpm -ivh /tmp/python-kitchen-1.2.6-9.el9.src.rpm
  args:
    creates: /usr/bin/dnf

- name: Install YUM using RPM
  command: rpm -ivh /tmp/yum-utils-1.1.31-28.fc21.noarch.rpm
  args:
    creates: /usr/bin/dnf

- name: Install Postfix
  dnf:
    name: postfix
    state: present

- name: Install Dovecot
  dnf:
    name: dovecot
    state: present

- name: Install Roundcube webmail
  dnf:
    name: roundcubemail
    state: present

- name: Configure Postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf

- name: Configure Dovecot
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf

- name: Configure Roundcube
  template:
    src: config.inc.php.j2
    dest: /etc/roundcubemail/config.inc.php

- name: Start and enable Postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Start and enable Dovecot
  service:
    name: dovecot
    state: started
    enabled: yes
