---
- name: Ensure we have sudo privileges
  command: whoami
  changed_when: false

- name: Update CentOS 7 repo URLs
  replace:
    path: /etc/yum.repos.d/CentOS-Base.repo
    regexp: 'mirrorlist=http://mirrorlist.centos.org'
    replace: '#mirrorlist=http://mirrorlist.centos.org'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Enable vault URLs for CentOS 7
  replace:
    path: /etc/yum.repos.d/CentOS-Base.repo
    regexp: '#baseurl=http://mirror.centos.org'
    replace: 'baseurl=http://vault.centos.org'
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Clean yum cache
  command: yum clean all
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Update apt cache (Debian/Ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Update yum cache (CentOS)
  yum:
    update_cache: yes
  when: ansible_distribution == 'CentOS'

- name: Update dnf cache (Fedora)
  dnf:
    update_cache: yes
  when: ansible_distribution == 'Fedora'