heat_template_version: 2021-04-16

description: Template for creating an environment with specific subnets and instances

parameters:
  environment_index:
    type: string
  key_name:
    type: string
  windows_2019_image:
    type: string
  debian_10_image:
    type: string
  ubuntu_18_image:
    type: string
  ubuntu_20_desktop_image:
    type: string
  splunk_image:
    type: string
  centos_7_image:
    type: string
  fedora_21_image:
    type: string
  public_net:
    type: string

resources:
  env_network:
    type: OS::Neutron::Net
    properties:
      name:
        str_replace:
          template: env-network-$index
          params:
            $index: { get_param: environment_index }

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: env_network }
      cidr:
        str_replace:
          template: 10.$index.1.0/24
          params:
            $index: { get_param: environment_index }
      gateway_ip:
        str_replace:
          template: 10.$index.1.1
          params:
            $index: { get_param: environment_index }

  user_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: env_network }
      cidr:
        str_replace:
          template: 10.$index.2.0/24
          params:
            $index: { get_param: environment_index }
      gateway_ip:
        str_replace:
          template: 10.$index.2.1
          params:
            $index: { get_param: environment_index }

  public_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: env_network }
      cidr:
        str_replace:
          template: 10.$index.3.0/24
          params:
            $index: { get_param: environment_index }
      gateway_ip:
        str_replace:
          template: 10.$index.3.1
          params:
            $index: { get_param: environment_index }

  env_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_net }

  router_interface_internal:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: env_router }
      subnet_id: { get_resource: internal_subnet }

  router_interface_user:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: env_router }
      subnet_id: { get_resource: user_subnet }

  router_interface_public:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: env_router }
      subnet_id: { get_resource: public_subnet }

  windows_2019_internal:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: windows-2019-internal-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: windows_2019_image }
      flavor: m1.medium
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: internal_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.1.10
              params:
                $index: { get_param: environment_index }

  debian_10_internal:
    type: OS::Nova::Server
    depends_on: windows_2019_internal
    properties:
      name:
        str_replace:
          template: debian-10-internal-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: debian_10_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: internal_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.1.11
              params:
                $index: { get_param: environment_index }

  ubuntu_18_user:
    type: OS::Nova::Server
    depends_on: debian_10_internal
    properties:
      name:
        str_replace:
          template: ubuntu-18-user-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: ubuntu_18_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: user_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.2.10
              params:
                $index: { get_param: environment_index }

  windows_2019_user:
    type: OS::Nova::Server
    depends_on: ubuntu_18_user
    properties:
      name:
        str_replace:
          template: windows-2019-user-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: windows_2019_image }
      flavor: m1.medium
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: user_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.2.11
              params:
                $index: { get_param: environment_index }

  ubuntu_20_desktop_user:
    type: OS::Nova::Server
    depends_on: windows_2019_user
    properties:
      name:
        str_replace:
          template: ubuntu-20-desktop-user-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: ubuntu_20_desktop_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: user_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.2.12
              params:
                $index: { get_param: environment_index }

  splunk_public:
    type: OS::Nova::Server
    depends_on: ubuntu_20_desktop_user
    properties:
      name:
        str_replace:
          template: splunk-public-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: splunk_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: public_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.3.10
              params:
                $index: { get_param: environment_index }

  centos_7_public:
    type: OS::Nova::Server
    depends_on: splunk_public
    properties:
      name:
        str_replace:
          template: centos-7-public-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: centos_7_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: public_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.3.11
              params:
                $index: { get_param: environment_index }

  fedora_21_public:
    type: OS::Nova::Server
    depends_on: centos_7_public
    properties:
      name:
        str_replace:
          template: fedora-21-public-$index
          params:
            $index: { get_param: environment_index }
      image: { get_param: fedora_21_image }
      flavor: m1.small
      key_name: { get_param: key_name }
      networks:
        - network: { get_resource: env_network }
          subnet: { get_resource: public_subnet }
          fixed_ip:
            str_replace:
              template: 10.$index.3.12
              params:
                $index: { get_param: environment_index }

outputs:
  env_network_id:
    description: ID of the environment network
    value: { get_resource: env_network }
