---
- name: Common tasks for all hosts
  hosts: all
  roles:
    - common

- name: Linux-specific common tasks
  hosts: all:!windows
  roles:
    - linux

- name: Windows-specific common tasks
  hosts: windows
  roles:
    - windows

- name: Install tools on Windows servers
  hosts: windows
  roles:
    - { role: windows_ad_dns_dhcp, when: "'internal' in inventory_hostname" }
    - { role: windows_docker_remote, when: "'user' in inventory_hostname" }

- name: Install tools on Debian servers
  hosts: debian
  become: yes
  roles:
    - debian_dns_ntp

- name: Install tools on Ubuntu servers
  hosts: ubuntu
  become: yes
  roles:
    - ubuntu_web

- name: Install tools on CentOS servers
  hosts: centos
  become: yes
  roles:
    - centos_ecomm

- name: Install tools on Fedora servers
  hosts: fedora
  become: yes
  roles:
    - fedora_webmail_webapps

- name: Install tools on Splunk servers
  hosts: splunk
  become: yes
  roles:
    - splunk

