---
- name: Linux-specific common tasks
  hosts: all:!windows
  any_errors_fatal: false
  roles:
    - linux

- name: Windows-specific common tasks
  hosts: windows
  any_errors_fatal: false
  roles:
    - windows

- name: Install tools on Windows servers
  hosts: windows
  any_errors_fatal: false
  roles:
    - { role: windows_ad_dns_dhcp, when: "'internal' in inventory_hostname", ignore_errors: yes }
    - { role: windows_docker_remote, when: "'user' in inventory_hostname", ignore_errors: yes }

- name: Install tools on Debian servers
  hosts: debian
  become: yes
  any_errors_fatal: false
  roles:
    - { role: debian_dns_ntp, ignore_errors: yes }

- name: Install tools on Ubuntu servers
  hosts: ubuntu
  become: yes
  any_errors_fatal: false
  roles:
    - { role: ubuntu_web, ignore_errors: yes }

- name: Install tools on CentOS servers
  hosts: centos
  become: yes
  any_errors_fatal: false
  roles:
    - { role: centos_ecomm, ignore_errors: yes }

- name: Install tools on Fedora servers
  hosts: fedora
  become: yes
  any_errors_fatal: false
  roles:
    - { role: fedora_webmail_webapps, ignore_errors: yes }

- name: Install tools on Splunk servers
  hosts: splunk
  become: yes
  any_errors_fatal: false
  roles:
    - { role: splunk, ignore_errors: yes }

